#
# Configuration of Utils plugin.
#

more-unbreaking-max-level: 10

spawner-allowed-worlds:
  - "TT"

prefix-set-command: "lp user %player% meta setprefix 1 %prefix%"
prefix-remove-command: "lp user %player% meta removeprefix 1 %prefix%"
suffix-set-command: "lp user %player% meta setsuffix 1 %suffix%"

legendary-ticket:
  display-name: "§6§lレジェンダリーチケット"
  lore:
    - "§7"
    - "§7おこチケ超大当たりで排出されるチケット。"
    - "§7超レア称号、スポナーなどと交換可能。"
    - ""
