#
# Configuration File of LazyUtils plugin.
#
# If you want use color code, use section §.

# MoreUnbreaking Max Level
MoreunbreakingMaxLevel: 10

# Plugin Messages
PermissionDenied: "§c権限がありません。"

#  utilities
HomeDirectory: "/minecraft/main/plugins/ImageMaps/images/"
HelpMessage: "§7これらのコマンドが使用可能です。"
DownLoadMessage: "§7ファイルがダウンロードされました。"
RemovedMessage: "§7ファイルは正常に削除されました。"
