name: ${project.artifactId}
version: ${project.version}
main: com.github.okocraft.utils.Utils
author: lazy_gon
api-version: '1.14'
commands:
  utils:
    description: Base command of this plugin.
    aliases: [lazy, lu]

permissions:
  utils.*:
    description: Includes all permissions.
    default: op
    children:
      utils.scoreranking: true
      utils.uniqueprefix.*: true
      utils.suffix.*: true
      utils.costrepair: true
  utils.uniqueprefix.*:
    description: Includes all uniqueprefix command's permission.
    default: op
    children:
      utils.uniqueprefix: true
      utils.uniqueprefix.add: true
      utils.uniqueprefix.set: true
      utils.uniqueprefix.remove: true
      utils.uniqueprefix.list: true
  utils.suffix.*:
    description: Includes all suffix command's permission.
    default: op
    children:
      utils.uniqueprefix: true
      utils.uniqueprefix.other: true
  utils.scoreranking:
    description: Permission for command /utils scoreranking <objective> top bottom
    default: op
  utils.uniqueprefix:
    description: Permission for command /utils uniqueprefix <args...>
    default: true
  utils.uniqueprefix.add:
    description: Permission for command /utils uniqueprefix add <prefix>
    default: op
  utils.uniqueprefix.set:
    description: Permission for command /utils uniqueprefix set <number>
    default: true
  utils.uniqueprefix.remove:
    description: Permission for command /utils uniqueprefix remove <number>
    default: true
  utils.uniqueprefix.list:
    description: Permission for command /utils uniqueprefix list
    default: true
  utils.uniqueprefix.other:
    description: Permission for other player argument of /utils uniqueprefix command
    default: op
  utils.suffix:
    description: Permission for /utils suffix command
    default: op
  utils.suffix.other:
    description: Permission for other player argument of /utils suffix command
    default: op
  utils.costrepair:
    description: Permission for command /utils costrepair [confirm]
    default: true
  utils.inactivemoney:
    description: Permission for command /utils inactivemoney [confirm]
    default: op
  utils.moreunbreaking:
    description: Permission for command /utils moreunbreaking
    default: true
  utils.bypass.creatinghall:
    description: Permission to bypass creating hall.
    default: op