name: ${project.artifactId}
version: ${project.version}
main: com.github.okocraft.utils.Utils
author: lazy_gon
api-version: '1.14'
softdepend: ["WorldEdit", "WorldGuard"]
commands:
  utils:
    description: "Base plugin command."
  pvparea:
    description: "Manipulate PvP area."
    aliases: [pa]
  uniqueprefix:
    description: "Manipulate Unique prefix."
    aliases: [upref]

permissions:
  utils.*:
    description: Includes all permissions.
    default: op
    children:
      utils.scoreranking: true
      utils.uniqueprefix.*: true
      utils.suffix.*: true
      utils.costrepair: true
      utils.inactivemoney: true
      utils.moreunbreaking: true
      utils.pvparea: true
  utils.uniqueprefix.*:
    description: Includes all uniqueprefix command's permission.
    default: op
    children:
      utils.uniqueprefix: true
      utils.uniqueprefix.add: true
      utils.uniqueprefix.set: true
      utils.uniqueprefix.remove: true
      utils.uniqueprefix.list: true
  utils.uniqueprefix:
    description: Permission for command /uniqueprefix <args...>
    default: true
  utils.uniqueprefix.add:
    description: Permission for command /uniqueprefix add <prefix>
    default: op
  utils.uniqueprefix.set:
    description: Permission for command /uniqueprefix set <number>
    default: true
  utils.uniqueprefix.remove:
    description: Permission for command /uniqueprefix remove <number>
    default: true
  utils.uniqueprefix.list:
    description: Permission for command /uniqueprefix list
    default: true
  utils.uniqueprefix.other:
    description: Permission for other player argument of /uniqueprefix command
    default: op
  utils.pvparea:
    description: Permission for command /pvparea [smashmode|itemunlimited] [true|false]
    default: true