name: LazyUtils
version: 1.0.0
main: com.github.okocraft.lazyutils.LazyUtils
author: lazy_gon
commands:
  uuidscoreboard:
    description: Commands that make uuid entries.
    usage: /uuidscoreboard <add|set|reset|remove|get> <objective> [number]
    aliases: [uscoreboard, uscore, usb]
    permission: lazyutils.uuidscoreboard
    permission-message: '§c<permission> の権限がありません'
  scoreranking:
    description: Command that shows vanilla scoreboard ranking in chat.
    usage: /scoreranking <objective> <top> <bottom>
    aliases: [scorerank, srank, sr]
    permission: lazyutils.scoreranking
    permission-message: '§c<permission> の権限がありません'

permissions:
  lazyutils.*:
    description: Includes all permissions.
    default: op
    children:
      lazyutils.uuidscoreboard.*: true
      lazyutils.scoreranking: true
  lazyutils.uuidscoreboard.*:
    description: Includes all uuidscoreboard command's permission.
    default: op
    children:
      lazyutils.uuidscoreboard: true
      lazyutils.uuidscoreboard.add: true
      lazyutils.uuidscoreboard.set: true
      lazyutils.uuidscoreboard.remove: true
      lazyutils.uuidscoreboard.get: true
      lazyutils.uuidscoreboard.ranking: true
  lazyutils.uuidscoreboard:
    description: Permission for command /uuidscoreboard
    default: op
  lazyutils.uuidscoreboard.add:
    description: Permission for command /uuidscoreboard add <player> <score> <number>
    default: op
  lazyutils.uuidscoreboard.set:
    description: Permission for command /uuidscoreboard set <player> <score> <number>
    default: op
  lazyutils.uuidscoreboard.remove:
    description: Permission for command /uuidscoreboard remove <player> <score> <number>
    default: op
  lazyutils.uuidscoreboard.get:
    description: Permission for command /uuidscoreboard get <player> <score>
    default: op
  lazyutils.scoreranking:
    description: Permission for command /scoreranking <objective> top bottom
    default: op
